obj1:
  name: 'VISIBLE_FLOOR'
  file: '/usr/local/share/choreonoid-1.6/model/misc/floor.wrl'
  translation: [0, 0, -0.1]
  rotation: [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
obj5:
  name: 'terrain'
  file: '../../jvrc_models/models/drc_terrain.wrl'
  translation: [1.85, 0.35, -0.1]
  rotation: [[0, -1, 0], [1, 0, 0], [0, 0, 1]]
